profile: {{ env['AWS_PROFILE'] }}
region:  {{ env['AWS_REGION'] }}
versioning: false
default_alias: head
clean_build: false
configuration:
  name: alexa-wpapi-wcs2016
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_function.lambda_handler
  description: AMIMOTO Alexa
  timeout: 20
  memory_size: 128
